// <auto-generated />
using System;
using FidgetPro.Fidgetmaster.Business.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FidgetPro.Fidgetmaster.Business.Migrations
{
    [DbContext(typeof(FidgetContext))]
    [Migration("20190814170408_fidget-approval")]
    partial class fidgetapproval
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FidgetPro.Fidgetmaster.Business.Models.Fidget", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApprovedBy");

                    b.Property<string>("Color");

                    b.Property<bool>("IsApproved");

                    b.Property<string>("Name");

                    b.Property<long>("TypeId");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("Fidgets");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Color = "Green",
                            IsApproved = false,
                            Name = "Foo",
                            TypeId = 2L
                        });
                });

            modelBuilder.Entity("FidgetPro.Fidgetmaster.Business.Models.FidgetType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DesignedDate");

                    b.Property<bool>("IsBouncing");

                    b.Property<bool>("IsFlying");

                    b.Property<bool>("IsSpinning");

                    b.Property<string>("TypeName");

                    b.HasKey("Id");

                    b.ToTable("FidgetTypes");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DesignedDate = new DateTime(2019, 8, 14, 17, 4, 8, 176, DateTimeKind.Utc).AddTicks(6584),
                            IsBouncing = false,
                            IsFlying = true,
                            IsSpinning = true,
                            TypeName = "Thingamajig"
                        },
                        new
                        {
                            Id = 2L,
                            DesignedDate = new DateTime(2019, 8, 14, 17, 4, 8, 176, DateTimeKind.Utc).AddTicks(8630),
                            IsBouncing = true,
                            IsFlying = false,
                            IsSpinning = true,
                            TypeName = "Domaflotitch"
                        },
                        new
                        {
                            Id = 3L,
                            DesignedDate = new DateTime(2019, 8, 14, 17, 4, 8, 176, DateTimeKind.Utc).AddTicks(8642),
                            IsBouncing = false,
                            IsFlying = false,
                            IsSpinning = false,
                            TypeName = "Chad"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp");

                    b.Property<string>("Email");

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail");

                    b.Property<string>("NormalizedUserName");

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FidgetPro.Fidgetmaster.Business.Models.Fidget", b =>
                {
                    b.HasOne("FidgetPro.Fidgetmaster.Business.Models.FidgetType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
